name: Android CI
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit Test
        run: ./gradlew jacocoTestReport
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step

      - name: Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.9.0
        with:
          api-level: 29
          arch: x86
          target: google_apis
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          script: ./gradlew connectedCheck executeScreenshotTests -PprintBase64